### ISSUE TITLE
Nodes must be re-added each time the program is executed

### ISSUE THREAD

**Issue by archwisp** [SecKC/SecKCoin#10]
I'm running this in a Windows 7 VM. Each time I run the app, I must re-add the nodes in order for it to sync and perform transactions.

**Comment by NoDataFound** [comment]
Resolved with https://github.com/SecKC/SecKCoin/pull/12  Thanks @hevnsnt !!!!

**Comment by hevnsnt** [comment]
You may have to start it with -conf=SecKCoin.conf
