### ISSUE TITLE
Get rid of the 'malware' and 'PUP' findings

### ISSUE THREAD

**Issue by ghost** [SecKC/SecKCoin#2]
Solutions off the top of my head would be to make it exactly like bitcoin/litecoin where people would mine the currency( voluntarily do the transaction and make a bit of coin doing so) instead of depending on peer-to-peer connections. And optimize the mining capability, e.g. make it optional or a completely separate utility from the wallet itself.

**Comment by NoDataFound** [comment]
Issue resolved by @hevnsnt and SKCv2 or no longer applies.
