### ISSUE TITLE
V2 Windows Client - No block chain

### ISSUE THREAD

**Issue by fcpchristopher** [SecKC/SecKCoin#25]
I backed up, then removed the v1 %appdata%/SecKCoin folder.  Then I ran the v2 client, shut it down, and copied the new SecKCoin.conf file as-is from here to that re-made directory.  Then I ran the v2 app again as admin and still get a message at the bottom of the client that says "no block source available..."
Here's my log so far:
[debug.log.txt](https://github.com/SecKC/SecKCoin/files/312890/debug.log.txt)

Win10Prox64
Connected to Sprint hotspot

**Comment by hevnsnt** [comment]
Can you paste your SecKCoin.conf file?  My guess is you are using a V1 conf (trying to connect to V1 nodes)

**Comment by NoDataFound** [comment]
@fcpchristopher is this issue still active?

**Comment by fcpchristopher** [comment]
The issue has been ameliorated. Thanks.
@hevnsnt @NoDataFound : sorry I missed the original request for the .conf file!
