### ISSUE TITLE
Why is the Makefile for LevelDB missing?

### ISSUE THREAD

**Issue by mollenkamp** [SecKC/SecKCoin#30]
I copied it into src/leveldb from this link in order to compile on debian 8.6

[Google LevelDB GitHub](https://github.com/google/leveldb/archive/v1.18.tar.gz)

I couldn't find this documented anywhere.

**Comment by NoDataFound** [comment]
Thanks!  I had this exact issue when building the wallet.  Here is how I fixed it:


First, I got the error below when trying to build the wallet.

👎 

```
~/SKC/SecKCoin/seckcoin/src $ make -f makefile.unix USE_UPNP=-
Building LevelDB ...
make[1]: Entering directory '/home/pi/SKC/SecKCoin/seckcoin/src/leveldb'
make[1]: *** No rule to make target 'libleveldb.a'.  Stop.
make[1]: Leaving directory '/home/pi/SKC/SecKCoin/seckcoin/src/leveldb'
makefile.unix:161: recipe for target 'leveldb/libleveldb.a' failed
make: *** [leveldb/libleveldb.a] Error 2
```

Then I did what you suggested
```
~/SKC/SecKCoin/seckcoin/src/leveldb $ wget https://github.com/google/leveldb/archive/v1.18.tar.gz
~/SKC/SecKCoin/seckcoin/src/leveldb $ tar xfv v1.18.tar.gz
```

This dumped all the files nice and neat into 

`~/SKC/SecKCoin/seckcoin/src/leveldb/leveldb-1.18`

So I did this:

`~/SKC/SecKCoin/seckcoin/src/leveldb/leveldb-1.18 $ cp Makefile ~/SKC/SecKCoin/seckcoin/src/leveldb/`

Then This:
`
~/SKC/SecKCoin/seckcoin/src $ make -f makefile.unix USE_UPNP=-`

Sucess!!! 👍 💯 
```

~/SKC/SecKCoin/seckcoin/src $ make -f makefile.unix USE_UPNP=-
Building LevelDB ...
make[1]: Entering directory '/home/pi/SKC/SecKCoin/seckcoin/src/leveldb'
g++ -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT -DSNAPPY -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/pi/SKC/SecKCoin/seckcoin/src -I/home/pi/SKC/SecKCoin/seckcoin/src/obj -DUSE_IPV6=1 -

[SNIP]
```

Find me at SecKC (@CoryKennedy) and I will buy you a beer!

**Comment by NoDataFound** [comment]
Resolved with 8f10870

**Comment by mollenkamp** [comment]
Thanks Cory!

**Comment by charliegama** [comment]
Please help,  error in compile 


************************


/bin/sh ../share/genbuild.sh obj/build.h

**Comment by mastermind999** [comment]
God bless you, works !
