### ISSUE TITLE
Sweep current .exe for vulnerabilities

### ISSUE THREAD

**Issue by ghost** [SecKC/SecKCoin#5]
For the tinfoil crowd, Also don't need a CVE with our name on it

**Comment by ghost** [comment]
Client-side penetrating testing isn't my forte, but the main CWE's we should be looking for are CWE-602(relying on the client-side to store data), CWE-94(Code Injection), CWE-398(bad code) and so on. Good list to keep in mind: http://cve.circl.lu/cwe

**Comment by NoDataFound** [comment]
Issue resolved by @hevnsnt and SKCv2 or no longer applies.
