### ISSUE TITLE
Process does not end when exiting

### ISSUE THREAD

**Issue by hsmkang** [SecKC/SecKCoin#7]
When the app is exited, it remains in system tray. System tray does not provide any menus. Killing the process seems to be the only way to restart the process.

**Comment by fcpchristopher** [comment]
I found that it DOES exit after a while.  Something like 5 min.  I'm going to try it again and time it.

![pasted image at 2016_05_27 08_47](https://cloud.githubusercontent.com/assets/19610309/15610060/000400e8-23e9-11e6-9d50-8680dbe1cd89.png)

**Comment by fcpchristopher** [comment]
**It took 00h_04m37s_ for the client to close itself.**

-After "closing" the client, the tray icon becomes unresponsive and the process is still found in the Task Manager.
-It held 33.6MB of RAM while waiting to finish shutting down.  Which is within 2MB of what it runs at. (similar on another computer with ~40MB)

*MSInfo32.exe dump for this PC: 
[Win8PC.txt](https://github.com/SecKC/SecKCoin/files/286618/Win8PC.txt)

I **am** finding that it stays open indefinitely on my Win10 laptop.

**Comment by fcpchristopher** [comment]
Psych!  As soon as I posted that, the process disappeared.
**00h05m28s** on my Win10 laptop.
[Win10PC.txt](https://github.com/SecKC/SecKCoin/files/286671/Win10PC.txt)

I tried it a 2nd time on my Win10 laptop and it took just under 7 min.  I missed the exact time.

**Comment by NoDataFound** [comment]
Issue resolved by @hevnsnt and SKCv2 or no longer applies.
