### ISSUE TITLE
Web browser capability

### ISSUE THREAD

**Issue by ghost** [SecKC/SecKCoin#9]
I was hoping eventually we could have a flask or django version of something like blockchain.info and attach it to seckc.org in the near future (It would make wallet management easier for the users and especially the staff who need to give out SKC to multiple people or teams at a time)

**Comment by NoDataFound** [comment]
This one is in the works and exists (in part) in the source.  Hosting and backend support needs to be considered.

**Comment by NoDataFound** [comment]
Issue resolved by @hevnsnt and SKCv2 or no longer applies.
